# 配置文件
# 系统配置
system:
  worker_number: 2 #单个账号的并发数
  delay: 2s #每个协程队列的延时
  max_queue_size: 100 #每个协程队列的最大值
  key: 1234567890qwerft #AES秘钥key

# 邮箱配置
emails:
- address:  example@example.com #邮箱地址
  server: smtp.exmail.example.com #smtp服务器地址
  port: 465 #端口号
  password: example #密码
- address:  example@example.com
  server: smtp.exmail.example.com
  port: 465
  password: example

